[package]
name = "pedantic"
version = "0.11.0"
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "pedantic"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
self_update = { version = "0.42", default-features = false, features = ["rustls", "archive-tar", "archive-zip", "compression-flate2"] }
pedantic-core = { path = "../pedantic-core" }
pedantic-service = { path = "../pedantic-service" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
