[package]
name = "pedantic-core"
version = "0.6.0"
edition = "2024"
license = "MIT"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
minijinja = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4"
